version: '3.8'
services:
  mydatabase:
    ports:
      - '3306:3306'
    image: mysql:8.0
    container_name: csrssrtest
    environment:
      MYSQL_ROOT_PASSWORD: cono # MySQL 루트 사용자 비밀번호 (원하는 비밀번호로 설정)
      MYSQL_USER: conouser # 생성할 데이터베이스 사용자 이름 (원하는 사용자 이름으로 설정)
      MYSQL_PASSWORD: conopassword
      MYSQL_DATABASE: conodb # 생성할 데이터베이스 이름 (원하는 데이터베이스 이름으로 설정)
    volumes:
      - customvolume:/var/lib/mysql
volumes:
  customvolume:
